function Hd = getFilter
%GETFILTER Returns a discrete-time filter System object.

% MATLAB Code
% Generated by MATLAB(R) 23.2 and DSP System Toolbox 23.2.
% Generated on: 26-Apr-2024 19:48:43

N    = 10;     % Order
F3dB = 1000;   % 3-dB Frequency
Fs   = 32000;  % Sampling Frequency

h = fdesign.lowpass('n,f3db', N, F3dB, Fs);

Hd = design(h, 'butter', ...
    'SystemObject', true,...
    UseLegacyBiquadFilter=true);


